### ISSUE TITLE
getInvoiceAsPdf: [404] Client error

### ISSUE THREAD

**Issue by Nachiket-git-dev** [XeroAPI/xero-php-oauth2#102]
Exception when calling AccountingApi->getInvoiceAsPdf: [404] Client error: `GET https://api.xero.com/api.xro/2.0/Invoices/736213a6-ed2a-4537-ab93-f910f53794a0/pdf` resulted in a `404 Not Found` response

Hi got this Exception when I try to get the invoice as pdf

**Comment by SidneyAllen** [comment]
@Nachiket-git-dev which version of the SDK are you using?  I recommend using version 1.5.2

**Comment by Nachiket-git-dev** [comment]
I think I have the latest one
this is how I call the function 
try {
    $result = $apiInstance->getInvoiceAsPdf($xero_tenant_id, $invoice_id,'application/pdf');
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling AccountingApi->getInvoiceAsPdf: ', $e->getMessage(), PHP_EOL;
}

**Comment by SidneyAllen** [comment]
Hey @Nachiket-git-dev - I would double check and make sure you've installed version 1.5.2

You see the trailing /pdf after the invoiceID number in your path... that was a bug in an early version of the SDK, but has since been resolved.

I've just tested the method getInvoiceAsPdf in our kitchen sync app and it works fine on version 1.5.2 of the SDK.
https://github.com/XeroAPI/xero-php-oauth2-app

```
// READ ALL 
$invoices = $apiInstance->getInvoices($xeroTenantId); 						
$invoiceId = $invoices->getInvoices()[0]->getInvoiceId();
$result = $apiInstance->getInvoiceAsPdf($xeroTenantId, $invoiceId, "application/pdf"); 						

// read PDF contents
$content = $result->fread($result->getSize());

//check if a temp dir exsits
$dir_to_save = "./temp/";
if (!is_dir($dir_to_save)) {
  mkdir($dir_to_save);
}
// write to temp dir
file_put_contents($dir_to_save . $result->getFileName() . ".pdf", $content);
```
