### ISSUE TITLE
Payment Terms Issue

### ISSUE THREAD

**Issue by Sam-Othman** [XeroAPI/xero-php-oauth2#121]
**SDK you're using (please complete the following information):**
 - Version 1.6.5

**Describe the bug**
Not sure if I am doing something wrong but Payment Terms will only show on contacts when using getContact() and specifying the contact. When using getContacts() for all contacts will return blank for payment_terms.

**To Reproduce**
1. Print both getContact() (for a contact with payment terms set) & also getContacts()
2. Check the payment_term key in both arrays
3. Compare the arrays
4. getContact() returns the payment_terms whereas getContacts() returns empty array

**Expected behavior**
payment_terms array should be populated on both functions

**Screenshots**
getContacts(): 
[contact_id] => 135a6560-ccdd-45c7-90cb-33eb0737333c
[payment_terms] => 

getContact():
[contact_id] => 135a6560-ccdd-45c7-90cb-33eb0737333c
[payment_terms] => XeroAPI\XeroPHP\Models\Accounting\PaymentTerm Object
                                        (
                                            [container:protected] => Array
                                                (
                                                    [bills] => XeroAPI\XeroPHP\Models\Accounting\Bill Object
                                                        (
                                                            [container:protected] => Array
                                                                (
                                                                    [day] => 20
                                                                    [type] => OFFOLLOWINGMONTH
                                                                )

                                                        )

                                                    [sales] => 
                                                )

                                        )

**Additional context**

**Comment by wobinb** [comment]
@Sam-Othman What you are seeing here is the expected behaviour. On many of our endpoints (Invoices being a good example) by default we return a summarised version if you request multiple items, and the full version when you request a single item.

You can get the full detail whilst requesting multiple contacts by including the page argument, eg.
getContacts($xero_tenant_id, $if_modified_since = null, $where = null, $order = null, $i_ds = null, **$page = null**, $include_archived = null)

Specifying the page argument as 1 will return the first 100 contacts that meet the criteria of your call in greater detail. Page as 2 will return the second 100 etc.
