### ISSUE TITLE
Bulk delete payments

### ISSUE THREAD

**Issue by andrews05** [XeroAPI/xero-php-oauth2#127]
This is not something that is shown in the Xero API docs, yet it's actually still possible to bulk delete payments the same way you would bulk delete/void anything else. Would we be able to get an "updateOrCreate" function for payments to allow this?

**Comment by SidneyAllen** [comment]
Hi @andrews05 

I understand what you are asking for, but at this moment the OpenAPI spec has defined both "createPayments" (which is a bulk create) on the POST. and "createPayment" on the PUT.  You can't define additional PUT/POSTs for these paths.

The only update action on payments allowed is the set the status to deleted.  While it might be useful to allow bulk delete - I don't think performing delete on individual payments is a blocker for anyone at this time.

Removing the singular "createPayment" and replacing it with "updateOrCreatePayment" method would be a breaking change across 6 different SDKs.

I don't think this is an issue that requires immediate action and could be rolled into a future larger breaking change across all SDKs.

Since this issue is related to our OpenAPI specs, if you wish to create a new issue in that repo, we'll tag it for future consideration.  I'll be closing this one under the PHP sdk.
