### ISSUE TITLE
Can not create new employees with bank details and super added

### ISSUE THREAD

**Issue by usmanmunirr** [XeroAPI/xero-php-oauth2#156]
**SDK you're using (please complete the following information):**
 - Version [e.g. 2.1.1]

**Describe the bug**
I am unable to create new employee via `createEmployee` function of payrollApiAu. Just simply adding the employee work fine but when bank details and super details are added as well the API is throwing error as 500 please contact xero.

**Code i am using to add employee.**

```
$employee = new XeroAPI\XeroPHP\Models\PayrollAU\Employee;
      $employee->setFirstName("Jakub");
      $employee->setLastName("A");
      $employee->setEmail("albus@hogwarts.edu");
      $dateOfBirth = DateTime::createFromFormat('m/d/Y', '05/29/2000');
      $employee->setDateOfBirthAsDate($dateOfBirth);
      $address = new XeroAPI\XeroPHP\Models\PayrollAu\HomeAddress;
      $address->setAddressLine1("101 Green St");
      $address->setCity("Island Bay");
      $address->setRegion(\XeroAPI\XeroPHP\Models\PayrollAu\State::NSW);
      $address->setCountry("AUSTRALIA");
      $address->setPostalCode("6023");
      $employee->setHomeAddress($address);

      $employee->setStartDate(new DateTime('2020-06-16'));
      $employee->setGender('M');
      $employee->setMobile('0410 888 888');
      $employee->setPhone('0410 888 888');
      $employee->setJobTitle('Developer Programmer');
      $employee->setPayrollCalendarID('70a8071b-505d-4580-bedc-739713f6e6f6');
      $employee->setOrdinaryEarningsRateId('dda6f8cf-9fa7-46e6-90a7-19b6aeca2cca');

      $bankAccount = new XeroAPI\XeroPHP\Models\PayrollAU\BankAccount;
      $bankAccount->setStatementText('Savings Account');
      $bankAccount->setAccountName('Jakub A');
      $bankAccount->setAccountNumber('10448888');
      $bankAccount->setBsb('063-888');
      
      $employee->setBankAccounts($bankAccount);
      $newEmployees = [];		
      array_push($newEmployees, $employee);  

      try {
          $result = $apiInstance->createEmployee($xero_tenant_id, $newEmployees);
          $data = json_decode($result['employees'][0]);
          echo $data->EmployeeID;
      } catch (\XeroAPI\XeroPHP\ApiException $e) {
        $error = PayrollAuObjectSerializer::deserialize($e->getResponseBody(), '\XeroAPI\XeroPHP\Models\PayrollAu\APIException',[]);
        var_dump($error);
        var_dump($e);
      }
```

**To Reproduce**
1. Unable to create new employee with banks accounts details and super details together 

**Expected behavior**
I should be able to add new employee with bank details and super details initially while creating them.

**Screenshots**
![image](https://user-images.githubusercontent.com/54349061/91509754-85205200-e91e-11ea-9a56-b5d3dd4ee6df.png)

**Additional context**

**Comment by SidneyAllen** [comment]
@usmanmunirr 

I ran a test in my demo app and found a few issues with how you are passing in the bank account details.

1. setBankAccounts is expecting an array of bank accounts
2. The bank account needs to have the setRemainder set to "true" otherwise you'll get a validation error
3. The BSB number can't have a dash in it.

The following code worked when tested.

$bankAccount = new XeroAPI\XeroPHP\Models\PayrollAU\BankAccount;
$bankAccount->setStatementText('Savings Account');
$bankAccount->setAccountName('Jakub A');
$bankAccount->setAccountNumber('10338888');
$bankAccount->setRemainder(true);
$bankAccount->setBsb('063890');
$newBankAccounts = [$bankAccount];	

$employee->setBankAccounts($newBankAccounts);
