### ISSUE TITLE
Listing of all the dependencies for manual copy because composer is not an option

### ISSUE THREAD

**Issue by vieroz** [XeroAPI/xero-php-oauth2#208]
**SDK you're using (please complete the following information):**
 - Version 2.4.3

**Is your feature request related to a problem? Please describe.**
Doesnt have the composer installed/can be installed/might not be an option to have it in.

**Describe the solution you'd like**
Listing of all the dependencies for manual copy the required libraries.

**Describe alternatives you've considered**
Maybe develop another simple OAuth 2.0 that doesnt require dotenv or league libs or any other external libs?
or perhaps they already exists somewhere out there?

**Additional context**

**Comment by SidneyAllen** [comment]
@vieroz - our SDK uses dependencies like thephpleague/oauth2-client and manage them using composer.  There isn't a way around that if you wish to use this library.

I am not sure how you'd perform the OAuth 2 authentication and make API calls without depending on other libraries.  I imagine it would be challenging and that is why libraries like thephpleague/oauth2-client and guzzle are open sourced and often used.

I would recommend finding a computer to do your development where you can install composer and use it to manage & install dependencies.  Once you've done that your code could be deployed to a server.  The one caveat if you go down this route, you'll want the version of PHP running on your local machine and server should match as composer will look at which version of PHP your computer is running and download the appropriate dependencies for that version.  Since we've never taken this approach, we won't be able to offer support or guidance as it's beyond the scope of our SDK.
