### ISSUE TITLE
Feature request: update multiple records

### ISSUE THREAD

**Issue by bluec** [XeroAPI/xero-php-oauth2#35]
Currently the client doesn't provide the feature to update multiple records at once.  It does however allow you to create multiple records at once.

E.g. currently there is a `createContacts()` method but no `updateContacts()` method (and same for other resources).

**Comment by SidneyAllen** [comment]
@bluec  Thanks for the feedback.  Working on this and should have a release to address this soon.

**Comment by abhinavrazz7272** [comment]
Hi Sidney,

I also faced the same issue while updating multiple Items . So I thought use the create Items(**createItems**) method without sending item_id and it will update the items because in docs only code is a required field but it didn't work.

Can you please let me know how can we update multiple items in one go? Is there any method for updating multiple items

**Comment by bluec** [comment]
@abhinavrazz7272 there is currently no method for updating multiple items - that's why this is a feature request. 

If you need to do it urgently (and I do) then you can write a class that extends  `XeroAPI\XeroPHP\Api\AccountingApi` and add your own methods for bulk updating records. The only real difference from the `createItems()` request is that update would use POST instead of PUT.

**Comment by abhinavrazz7272** [comment]
@bluec Thank you for your suggestion. I have already do the same as you suggested.

Now I can create/update multiple records.

**Comment by SidneyAllen** [comment]
@abhinavrazz7272 @bluec - checkout version 1.1.2
