### ISSUE TITLE
Versioning strategy

### ISSUE THREAD

**Issue by fooman** [XeroAPI/xero-php-oauth2#46]
Would it be possible to adopt a stricter versioning strategy along the lines of semver.org?

You noted in the readme the breaking change which is great. Unfortunately with this standard workflow it would break for end users fairly quickly

`composer require xeroapi/xero-php-oauth2`

This in the past would have installed let's say version 1.0.5. Composer would have defaulted to using a version constraint of ^1.0.

If one would have used createInvoice and then subsequently ran 
`composer update` this would ensue to breakage as this would update to version 1.1.0 without hesitation.

Instead of bumping to 1.1.0 going directly to 2.0.0 would have given a chance to act on this.

**Comment by fooman** [comment]
Additionally removing support for major branches of php I would also consider a major change. Any chance this can be widened again? While I appreciate that older php versions are no longer maintained other applications do not always move as fast. 

Was there something in the DateTime fix that was only possible from php 7.2 onwards?

**Comment by SidneyAllen** [comment]
@fooman - thanks for the feedback.  This SDK is only a few months old and we are still working through things.  I'll keep in mind your comment about breaking changes as it relates to versioning in the future.

On the topic of "removing support for major branches of php".  I'm currently running 7.2 on my machine and have been testing the SDK on this version.  We had listed 5.5 as the supported version (as that was the default for our code generator templates we are utilizing).  We received  feedback the SDK didn't run on 5.5.

The fact that support for 7.2 ended in Nov 2020 - I thought version was a reasonable cut off. https://en.wikipedia.org/wiki/PHP

This is a long way of saying, I'm happy to widen the requirements for the version of PHP but would like help from the community to validate older versions and let us know.

**Comment by calcinai** [comment]
@SidneyAllen Have a look at [this packagist blog post](https://blog.packagist.com/php-versions-stats-2019-2-edition/) - it isn't the most recent, but there are still many PHP5 users out there.

**Comment by SidneyAllen** [comment]
@calcinai - thanks for the blog post.  The decision on how many versions back to support can be tricky.   Several factors like the importance of on going security patches and maintenance is def. top of mind.  

This issue was raised saying 5.5.29 wasn't supported
https://github.com/XeroAPI/xero-php-oauth2/issues/36

Like I said previously, support for 7.2 ended in Nov 2020 - I thought version was a reasonable cut off. https://en.wikipedia.org/wiki/PHP (that's the version I'm running and testing against)

I'll be closing this issue - but if anyone wishes to fork this repo and test on earlier versions of PHP and validate it works or suggest reasonable changes to extend support I'm all ears.
