### ISSUE TITLE
A Few Usability Enhancements

### ISSUE THREAD

**Issue by hailwood** [XeroAPI/xero-php-oauth2#51]
I imagine a lot of this is to do with the API being generated from the OpenAPI spec but I thought I'd run the ideas through here anyway to see if we can update the moustache templates to support them.

# Table of Contents
* [Can we just set the tenant ID on the Configuration class?](#user-content-point_1)
* [Can we make the `getX` methods return a single item rather than the collection?](#user-content-point_2)
* [Can we make `ArrayAccess` on the collections reference the internal collections, and also implement `Countable`, `IteratorAggregate` and `JsonSerializable`?](#user-content-point_3)
* [Can we make the lists take an array of items directly?](#user-content-point_4)
* [Can we make the `createX`,`updateOrCreateX`, `createXs`, `updateOrCreateXs` methods consistent?](#user-content-point_5)

# <a name="point_1"></a>Can we just set the tenant ID on the Configuration class?

## Explanation
Rather than doing something like

```php
$config = Configuration::getDefaultConfiguration();
$config->setHost('https://api.xero.com/api.xro/2.0);
$config->setAccessToken($accessToken);

$api = new AccountingApi(new GuzzleClient(), $config);

$api->getContacts($tenantId);
$api->getContact($tenantId, $contactId);
$api->createContactsContacts($tenantId, $contactsList);
```

Why can't we just set the tenantId on the configuration like the access token?
```php
$config = Configuration::getDefaultConfiguration();
$config->setHost('https://api.xero.com/api.xro/2.0);
$config->setAccessToken($accessToken);
$config->setTenantId($tenantId);

$api = new AccountingApi(new GuzzleClient(), $config);

$api->getContacts();
$api->getContact($contactId);
$api->createContactsContacts($contactsList);
```

## Reasoning
Right now we have to keep track of the tenantId and inject it from somewhere, every time we want to use the API, that means that in a system where we use dependency injection (e.g. Laravel) we can't just inject an instance of `AccountingApi` that's preconfigured, we need to inject the `AccountingApi` instance and either load the tenantId from a cache, or inject something else that knows about it.

# <a name="point_2"></a>Can we make the `getX` methods return a single item rather than the collection?

## Explanation

Right now if we want to get a single contact we need to use

```php
$api = new AccountingApi(new GuzzleClient(), $config);

// To get a single thing we do...
$list = $api->getContact($tenantId, $contactId); // Contacts instance with one item
$contact = $list->getContacts()[0]; // Contact instance
```

Which is a bit strange, since `getSingularThing` returns a list.
It would be much better if we could do

```php
$api = new AccountingApi(new GuzzleClient(), $config);

// To get a single thing we do...
$contact = $api->getContact($tenantId, $contactId); // Contact instance
```

## Reasoning
It's just cleaner!

# <a name="point_3"></a>Can we make `ArrayAccess` on the collections reference the internal collections, and also implement `Countable`, `IteratorAggregate` and `JsonSerializable`?

## Explanation

Presently the generator spits out (truncated to what matters)

```php
class Contacts implements ModelInterface, ArrayAccess
{
    
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

}
```

Which means if you really want you can do 

```php
$api->getContacts($tenantId)['contacts'];
```

instead of 
```php
$api->getContacts($tenantId)->getContacts();
```

But it's a bit pointless, and we always need to do `->getThings()` before you can do anything with it.

If we updated the generator to spit out the following 

```php
class Contacts implements ModelInterface, ArrayAccess, Countable, IteratorAggregate, JsonSerializable
{
    
    public function offsetExists($offset)
    {
        return isset($this->container['contacts'][$offset]);
    }

    public function offsetGet($offset)
    {
        return isset($this->container['contacts'][$offset]) ? $this->container['contacts'][$offset] : null;
    }

    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container['contacts'][] = $value;
        } else {
            $this->container['contacts'][$offset] = $value;
        }
    }

    public function offsetUnset($offset)
    {
        unset($this->container['contacts'][$offset]);
    }

    public function count() 
    {
        return count($this->container['contacts']);
    }

    public function getIterator() 
    {
        return new ArrayIterator($this->container['contacts']);
    }

    public function jsonSerialize()
    {
        return AccountingObjectSerializer::sanitizeForSerialization($list)->Contacts;
    }

}
```

Then it makes it much more friendly to use

## Reasoning

```php

//convert to json (current)
$list = api->getContacts($tenantId);
$forSerialization = AccountingObjectSerializer::sanitizeForSerialization($list);
json_encode($forSerialization->Contacts);

//convert to json (new)
json_encode($api->getContacts($tenantId));

// count (current)
count($api->getContacts($tenantId)->getContacts());

// count (new)
count($api->getContacts($tenantId));
// also allows by virtue
$api->getContacts($tenantId)->count();

// loop (current)
foreach($api->getContacts($tenantId)->getContacts() as $contact) { ... }

// loop (new)
foreach($api->getContacts($tenantId) as $contact) { ... }

// get specific offset (current)
$api->getContacts($tenantId)->getContacts()[1]

// get specific offset (new)
$api->getContacts($tenantId)[1]

// replace contact (current)
$contactsList = $api->getContacts($tenantId);
$updatedContacts = $contactsList->getContacts();
$updatedContacts[3] = $anUpdatedContact;
$contactsList->setContacts($updatedContacts);

// replace contact (new)
$contactsList = $api->getContacts($tenantId);
$contactsList[3] = $anUpdatedContact;

// unset contact (current)
$contactsList = $api->getContacts($tenantId);
$updatedContacts = $contactsList->getContacts();
unset($updatedContacts[3]);
$contactsList->setContacts($updatedContacts);

// unset contact (new)
$contactsList = $api->getContacts($tenantId);
unset($contactsList[3]);
```

# <a name="point_4"></a>Can we make the lists take an array of items directly?

## Explanation
Right now we can do either

```php
$list = new Contacts();
$list->setContacts($arrayOfContacts);
```
or
```php
$list = new Contacts(['contacts' => $arrayOfContacts]);
```

But the constructors never use anything except that single key, so why don't we clean it up so we can just do

```php
$list = new Contacts($arrayOfContacts);
```

## Reasoning
It's just cleaner!

# <a name="point_5"></a>Can we make the `createX`, `updateOrCreateX`, `createXs`, `updateOrCreateXs` methods consistent?

## Explanation
Right now the rules for whether we have `createX`,`updateOrCreateX`, `createXs`, `updateOrCreateXs` seem rather random.

Take for example Invoices, where [the endpoint doesn't seem to support creating multiple invoices in one go](https://developer.xero.com/documentation/api/invoices), but the methods we have are:

| method | actually exists | should exist |
|-|-|-|
| createInvoice | no | yes |
| updateInvoice | no | yes |
| createInvoices | yes | no |
| updateOrCreateInvoices | yes | no |

Then there's Accounts where [the endpoint specifically states you cannot create multiple in one go](https://developer.xero.com/documentation/api/accounts), this one is right:

| method | actually exists | should exist |
|-|-|-|
| createAccount | yes | yes |
| updateAccount | yes | yes |
| createAccounts | no | no |
| updateOrCreateAccounts | yes | no |

Then there's Contacts where [the endpoint specifically states you can create multiple in one go](https://developer.xero.com/documentation/api/contacts):

| method | actually exists | should exist |
|-|-|-|
| createContact | no | yes |
| updateContact | yes | yes |
| createContacts | yes | yes |
| updateOrCreateContacts | yes | yes |

Then there's Employees where [the endpoint specifically states you can create multiple in one go](https://developer.xero.com/documentation/api/employees):

| method | actually exists | should exist |
|-|-|-|
| createEmployee | yes | yes |
| updateEmployee | yes | yes |
| createEmployees | yes | yes |
| updateOrCreateEmployees | no | yes |

Now there was talk in #47 about replacing `createX` with `updateOrCreateX` which is fine, as long as the rules are **consistent**.

## Reasoning
With the existence of the methods being all over the place it makes it difficult to intuitively learn the API, instead you need to hope the method exists for each entity.

**Comment by lukecurtis93** [comment]
Agree with all of these. 

Now the docs reference this package as the preferred PHP implementation there's a lot of quirks here that don't really follow convention - these suggestions are a great start to sort them out 👍

**Comment by calcinai** [comment]
@SidneyAllen happy to help out here if I can.

**Comment by filliph** [comment]
I was just about to report all of these, as well as the fact that a lot of `createX` methods randomly disappeared from the code, but remains in the docs, at some point recently.

It's incredibly inconvenient to create new assets now:

I've had to create a wrapper method like so:
```php
	public function createInvoice(\XeroAPI\XeroPHP\Models\Accounting\Invoice $invoice)
	{
		$invoices = new \XeroAPI\XeroPHP\Models\Accounting\Invoices([
			'invoices' => [$invoice]
		]);

		$response = $this->getXeroApp()
			->createInvoices($tenantId, $invoices);

		$invoice->setInvoiceId($response->getInvoices()[0]->getInvoiceId());
	}
```

7 lines of code for what should be 1 single line of code (a `save` method on the `Invoice` model).

**Comment by SidneyAllen** [comment]
@hailwood 

We appreciate you taking the time to provide this feedback - nice formatting ;-)   but should share that for 2020 we are focused on high priorities issues that are preventing developers from using our SDKs (missing endpoints, bugs, documentation, etc)

As you pointed out, our OAuth 2.0 SDKs are now generated from our OpenAPI specs. This approach does have some limitations. Feedback that requires changes to the specs is carefully considered as it may impact other SDKs (languages)as well as sample apps and documentation.

**Can we just set the tenant ID on the Configuration class?**

- This question relates to our OpenAPI spec, so I've created an issue in that repo to continue a conversation around this question with the community.

https://github.com/XeroAPI/Xero-OpenAPI/issues/149

**Can we make the getX methods return a single item rather than the collection?**

- Where Xero's API returns an array of objects, we've defined the response in the OAS to reflect this.

Your example of $list = $api->getContact($tenantId, $contactId); returns an Array of Contacts with a single object, so the code accurately reflects the API.  While we could explore extending the spec to indicate a single object in the response  and tweak the mustache templates, this isn't something we'd prioritize at this point in time.

**Can we make ArrayAccess on the collections reference the internal collections, and also implement Countable, IteratorAggregate and JsonSerializable?**
- No promises, but this could be explored. I've created a new issue to keep it open.
https://github.com/XeroAPI/xero-php-oauth2/issues/63

**Can we make the lists take an array of items directly?**
- I hear you about it being "cleaner" but I don't see this as a high priority for 2020.

$list = new Contacts(['contacts' => $arrayOfContacts]); 
and
$list = new Contacts($arrayOfContacts);

These are not radically different.

**Can we make the createX, updateOrCreateX, createXs, updateOrCreateXs methods consistent?**

So, this is where OpenAPI specs runs head on into our overly flexible API.

In OAS, a path can only be defined once and method on each path can only be defined once.

POST /Invoices
In the body, you have the option of passing an Invoice object OR and Array of Invoices.  The response in either situation is an Array of Invoices.

With OAS, we needed to choose which one (createInvoice or createInvoices) and createInvoices will work for both singular and plural Invoices, so we've chosen that.

PUT  /Invoices
Performing an updateOrCreate is supported so you can pass multiple objects and if it exists then update and if not create.

The pattern above is applied to endpoints that support both singular and bulk update and create.

BankTransactions
Contacts
CreditNotes
Invoices
Items
PurchaseOrders
Quotes

This is why createInvoice and createContact can not be included... your table is a bit out of date - as the most recent OAS, updateInvoice exists (and has for some time) and updateOrCreateAccounts does not exist.

I'll look at Employees to the see if it should follow the pattern above for createEmployees and updateOrCreateEmployees.

Our API is over a decade old and we've reverse engineered these OpenAPI specs from our documentation (no mean feat), so we appreciate this feedback as we continue to improve the specs that our SDKs are built from.

**Comment by calcinai** [comment]
@SidneyAllen I wonder what would happen if I ran the generator over the docs again today...

**Comment by SidneyAllen** [comment]
@hailwood @filliph @lukecurtis93 

I wanted to let you know I've implemented your suggestion to "implement Countable, IteratorAggregate and JsonSerializable" in version 1.6.2 of the xero-php-oauth2 SDK.  Appreciate you taking the time to share your feedback.

https://github.com/XeroAPI/xero-php-oauth2/issues/63

I've also done some testing with PHP 5.6 and have lowered the requirement for the SDK to 5.6+

**Comment by andrews05** [comment]
Re: "Can we make the getX methods return a single item rather than the collection?"

I know you said this isn't a priority, but could we split it off into a new issue just so it isn't forgotten?
