### ISSUE TITLE
Update or Delete Payment Validation error

### ISSUE THREAD

**Issue by chirag2324** [XeroAPI/xero-php-oauth2#91]
**SDK you're using (please complete the following information):**
 - Version [1.4]

**Describe the bug**
Update or Delete Payment

Code as below:

`$payment = $apiInstance->getPayment($xeroTenantId,"300c0769-1407-483e-a473-ad0d9d3f6e1a");
                    //dd($payment['payments'][0]);
                    //$payment['payments'][0]->setAmount(1900);

                    $apiResponse = $apiInstance->deletePayment($xeroTenantId,"300c0769-1407-483e-a473-ad0d9d3f6e1a",$payment);`

**To Reproduce**

**Expected behavior**
Validation error occurred

**Screenshots**
![127 0 0 1 8000 xero_exchange action 8 (1)](https://user-images.githubusercontent.com/55869433/77995372-496e6580-7349-11ea-9c4f-4059864131c9.png)

**Additional context**

**Comment by MattR-Api** [comment]
Hi @chirag2324 

Thanks for getting in touch. As this is a validation error and not related to the PHP SDK, I'll shut this issue down. 

To answer your questions however, as it mentions in the Error, you're not able to update Payments. Usually items can only be updated when they are in a DRAFT Status, however Payments only have AUTHORISED and DELETED. Due to this, you must delete any payments applied to your Invoices/credit notes, then create a new one with the updated details. 

If you need any further information, please see the link below, or get in touch with the support team at api@xero.com 

Xero Developer: 
[Payments](https://developer.xero.com/documentation/api/payments)
[Payments Statues](https://developer.xero.com/documentation/api/types#PaymentStatusCodes)

Matt
